// +build go1.9

package main

var (
	cmdlist = []string{
		"github.com/u-root/u-root/cmds/cat",
		"github.com/u-root/u-root/cmds/cp",
		"github.com/u-root/u-root/cmds/cpio",
		"github.com/u-root/u-root/cmds/date",
		"github.com/u-root/u-root/cmds/dd",
		"github.com/u-root/u-root/cmds/dhclient",
		"github.com/u-root/u-root/cmds/dirname",
		"github.com/u-root/u-root/cmds/dmesg",
		"github.com/u-root/u-root/cmds/grep",
		"github.com/u-root/u-root/cmds/hexdump",
		"github.com/u-root/u-root/cmds/hostname",
		"github.com/u-root/u-root/cmds/ed",
		"github.com/u-root/u-root/cmds/gpt",
		"github.com/u-root/u-root/cmds/init",
		"github.com/u-root/u-root/cmds/insmod",
		"github.com/u-root/u-root/cmds/io",
		"github.com/u-root/u-root/cmds/ip",
		"github.com/u-root/u-root/cmds/kill",
		"github.com/u-root/u-root/cmds/lddfiles",
		"github.com/u-root/u-root/cmds/ln",
		"github.com/u-root/u-root/cmds/losetup",
		"github.com/u-root/u-root/cmds/ls",
		"github.com/u-root/u-root/cmds/mkdir",
		"github.com/u-root/u-root/cmds/mknod",
		"github.com/u-root/u-root/cmds/mount",
		"github.com/u-root/u-root/cmds/msr",
		"github.com/u-root/u-root/cmds/mv",
		"github.com/u-root/u-root/cmds/netcat",
		"github.com/u-root/u-root/cmds/pci",
		"github.com/u-root/u-root/cmds/ping",
		"github.com/u-root/u-root/cmds/ps",
		"github.com/u-root/u-root/cmds/pwd",
		"github.com/u-root/u-root/cmds/rm",
		"github.com/u-root/u-root/cmds/readlink",
		"github.com/u-root/u-root/cmds/rush",
		"github.com/u-root/u-root/cmds/shutdown",
		"github.com/u-root/u-root/cmds/sleep",
		"github.com/u-root/u-root/cmds/tcz",
		"github.com/u-root/u-root/cmds/umount",
		"github.com/u-root/u-root/cmds/uname",
		"github.com/u-root/u-root/cmds/wget",
		"github.com/u-root/u-root/cmds/wifi",
		"github.com/u-root/u-root/cmds/xinit",
		"github.com/u-root/NiChrome/install",
		"github.com/u-root/NiChrome/uinit",
	}
)
